### ISSUE TITLE
预览与排序文字排版错乱，以及评论的时候表情为什么竖着显示？？

### ISSUE THREAD

**Issue by xiaoyan94** [jzwalk/Smilies#1]
- 预览与排序文字排版错乱
![image](https://user-images.githubusercontent.com/17242539/31725941-2b6b6964-b458-11e7-9b72-169a7f25bacd.png)
 - 表情为什么竖着显示
![image](https://user-images.githubusercontent.com/17242539/31725995-4a162aca-b458-11e7-9bec-6a8781416c10.png)
 - 我的主题是Next

**Comment by xiaoyan94** [comment]
- 第一个是img标签display属性的原因。
![image](https://user-images.githubusercontent.com/17242539/31731609-2fc75314-b468-11e7-95c0-340b6c5ed180.png)

 - 不过第一个问题解决不了

**Comment by jzwalk** [comment]
新版已经重新调整了显示效果。感谢你的css修正！(标签改span也是默认横排)
