### ISSUE TITLE
我将函数放在首页，但是没有效果，其他页面就没有问题

### ISSUE THREAD

**Issue by chinobing** [jzwalk/Smilies#3]
![20180311152730](https://user-images.githubusercontent.com/27722028/37250865-ab7535fa-2540-11e8-8f39-00cce9062d03.png)

就是这样，点击没有反应。其他页面没有问题。
这个“吐槽框”只有管理员才能看见的。
网址：http://www.bingwong.org

**Comment by jzwalk** [comment]
你这个需求比较特殊……考虑到首页一版没有评论框，插件并没有往首页输出js。你可以手动修改[Plugin.php的第629行](https://github.com/jzwalk/Smilies/blob/bfa0184bb4fe3192df09d701493c67ab6afa8c91/Plugin.php#L629)改成
`if ($widget->is('single') || $widget->is('index')) {`即可。

**Comment by chinobing** [comment]
按照你的方法改了，但是完全没有显示出来？ 
如果用旧的版本，```<div id="smiliesbox" style="display:block;">。。。。</div>```是可以正常显示，但是js无效。但现在用了新的版本，连<DIV>的代码都没有出现，我怀疑是调用问题

**Comment by chinobing** [comment]
513行：
```
	public static function insertjs($widget)
	{
		$options = Helper::options();
		$settings = $options->plugin('Smilies');
		$textareaid = $settings->textareaid;
		$textareaid = $textareaid ? $textareaid : _t('一般无需填写');

		$idset = ($widget->is('single') || $widget->is('index')) ? $textareaid : 'text';
		$txtid = $settings->jqmode ? '#'.$idset : $idset;
		$txtdom = 'domId("'.$txtid.'")';
		if ($widget->is('single') || $widget->is('index') && $idset==_t('一般无需填写')) {
			$txtid = 'textarea';
			$txtdom = 'domTag("'.$txtid.'")';
		}
```

629行：
```
		if ($widget->is('single') || $widget->is('index')) {
```
因为只改动629的代码并没有效果，而且div并没有调用，所以我改了513行的代码，但同样没有效果。

**Comment by jzwalk** [comment]
$comments变量默认只在评论模版里声明，所以你在首页用新版代码无效了。可以用旧版代码`<?php Smilies_Plugin::output(); ?>`也是兼容的。js无效有两种可能，一个是你用的主题没有在footer.php里按标准写上插件节点`<?php $this->footer(); ?>`，二就是其他js代码和表情插入js冲突了。

**Comment by chinobing** [comment]
果然优秀！！！而且解释得很清楚！

**Comment by jzwalk** [comment]
能用上就行:P
