### ISSUE TITLE
php5.6.27无法扫描表情文件夹

### ISSUE THREAD

**Issue by eeg1412** [jzwalk/Smilies#4]
会报错

`Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

Warning: Cannot modify header information - headers already sent in D:\WWW\wikimoe\typecho\var\Typecho\Response.php on line 165

Warning: Cannot modify header information - headers already sent in D:\WWW\wikimoe\typecho\var\Typecho\Response.php on line 165
"[{\"qq\":[\"icon_arrow.gif\",\"icon_biggrin.gif\",\"icon_confused.gif\",\"icon_cool.gif\",\"icon_cry.gif\",\"icon_eek.gif\",\"icon_evil.gif\",\"icon_exclaim.gif\",\"icon_idea.gif\",\"icon_lol.gif\",\"icon_mad.gif\",\"icon_mrgreen.gif\",\"icon_neutral.gif\",\"icon_question.gif\",\"icon_razz.gif\",\"icon_redface.gif\",\"icon_rolleyes.gif\",\"icon_sad.gif\",\"icon_smile.gif\",\"icon_surprised.gif\",\"icon_twisted.gif\",\"icon_wink.gif\"],\"tieba\":[\"icon_mrgreen.png\",\"icon_neutral.png\",\"icon_twisted.png\",\"icon_arrow.png\",\"icon_eek.png\",\"icon_smile.png\",\"icon_confused.png\",\"icon_cool.png\",\"icon_evil.png\",\"icon_biggrin.png\",\"icon_idea.png\",\"icon_redface.png\",\"icon_razz.png\",\"icon_rolleyes.png\",\"icon_wink.png\",\"icon_cry.png\",\"icon_surprised.png\",\"icon_lol.png\",\"icon_mad.png\",\"icon_sad.png\",\"icon_exclaim.png\",\"icon_question.png\"],\"weibo\":[\"icon_mrgreen.png\",\"icon_neutral.png\",\"icon_twisted.png\",\"icon_arrow.png\",\"icon_eek.png\",\"icon_smile.png\",\"icon_confused.png\",\"icon_cool.png\",\"icon_evil.png\",\"icon_biggrin.png\",\"icon_idea.png\",\"icon_redface.png\",\"icon_razz.png\",\"icon_rolleyes.png\",\"icon_wink.png\",\"icon_cry.png\",\"icon_surprised.png\",\"icon_lol.png\",\"icon_mad.png\",\"icon_sad.png\",\"icon_exclaim.png\",\"icon_question.png\"],\"wordpress\":[\"icon_mrgreen.png\",\"icon_neutral.png\",\"icon_twisted.png\",\"icon_arrow.png\",\"icon_eek.png\",\"icon_smile.png\",\"icon_confused.png\",\"icon_cool.png\",\"icon_evil.png\",\"icon_biggrin.png\",\"icon_idea.png\",\"icon_redface.png\",\"icon_razz.png\",\"icon_rolleyes.png\",\"icon_wink.png\",\"icon_cry.png\",\"icon_surprised.png\",\"icon_lol.png\",\"icon_mad.png\",\"icon_sad.png\",\"icon_exclaim.png\",\"icon_question.png\"]},\"qq<\\\/option>tieba<\\\/option>weibo<\\\/option>wordpress<\\\/option>\",\"`

**Comment by jzwalk** [comment]
这个是你的php.ini配置有问题，按这句要求改下就好：To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini
